# Generated by Django 4.2.11 on 2024-04-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
