# Generated by Django 4.2.11 on 2024-04-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(upload_to='recipes', default='no-picture.jpg'),
        ),
    ]
