# Generated by Django 4.2.11 on 2024-04-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('e', 'Easy'), ('m', 'Medium'), ('i', 'Intermediate'), ('h', 'Hard')], default='e', max_length=15),
        ),
    ]
