# Generated by Django 4.2.11 on 2024-05-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.FloatField(help_text='in minutes', verbose_name='Cooking Time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=200, verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='note',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, default='no-picture.jpg', null=True, upload_to='recipes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=50, verbose_name='Recipe Name'),
        ),
    ]
